### ISSUE TITLE
error -"user did not confirm javascript access was enabled. exiting due to insufficient permissions"

### ISSUE THREAD

**Issue by ginakiele5** [ahertel/wholefoods-delivery-slot-finder#27] opened 2020-04-08 18:16 UTC
Got an error on first run: cannot get window id1907. Also got this: "user did not confirm javascript access was enabled. exiting due to insufficient permissions." Does anyone know how to fix it?

**Comment by ahertel** [comment] 2020-04-08 18:23
@ginakiele5 Did you enable "Allow JavaScript from Apple Events"? I recently updated the [Instructions](https://github.com/ahertel/Amazon-Fresh-Whole-Foods-delivery-slot-finder#instructions) with this [how-to video](https://www.youtube.com/watch?v=S6zb_6yTAbo). Please check it out the video to ensure you have the right permissions enabled let me know if you're still having issues. Thanks!

**Comment by ginakiele5** [comment] 2020-04-08 18:31
Thank you Adrian!

**Comment by ahertel** [comment] 2020-04-08 18:58
@ginakiele5 Is the script working for you now? Asking so I know whether to close this issue out.

**Comment by ginakiele5** [comment] 2020-04-08 19:04
Hi Adrian.
Thank you so much for developing this script.  I plan on making a donation on your page.  And good luck to your parents. You’re a good son!
I already have the javascript enabled so not sure what was going on.  I reran the script and it looks likes it’s running but I haven’t gotten any hits on the Amazon site yet…waiting patiently.
I will keep you posted! And thanks again!
Gina

**Comment by ginakiele5** [comment] 2020-04-08 19:17
Hi Adrian,
Just got this message. 
Result:
error "Safari got an error: You must enable the 'Allow JavaScript from Apple Events' option in Safari's Develop menu to use 'do JavaScript'." number 8

 Went back in and allowed javascript for apple events again. Fingers crossed again!
Gina

**Comment by ginakiele5** [comment] 2020-04-08 19:19
Sorry to inundate you!  Just got this error too.
Result:
error "Safari got an error: Can’t get window id 2295." number -1728 from window id 2295

**Comment by ahertel** [comment] 2020-04-08 19:47
@ginakiele5 No worries about inundation. In fact, I appreciate the updates. Are you possibly quitting Safari or closing the window used by the script at any point?

**Comment by ginakiele5** [comment] 2020-04-08 19:53
No keeping it open

**Comment by ginakiele5** [comment] 2020-04-08 21:03
HI Aiden,
Just wanted to let you know that I think it’s working now.  I’ve gotten 2 delivery spots but they’re gone by the time my credit card is accepted.  I’ll keep trying and thank you so much for your help!
I hope your parents are well!
Gina

**Comment by ahertel** [comment] 2020-04-09 00:44
@ginakiele5 Great to hear that it's working for you now. I'd still love to find out what was causing your issue, so if you encounter it again, could you please follow these steps in [this video](https://youtu.be/wGKfNLzDx-s) I made for you to share the script's log with me? That might help me identify the cause.

Re: the unsuccessful slots, unfortunately you may encounter many more these. You may have read my [disclaimer](https://github.com/ahertel/Amazon-Fresh-Whole-Foods-delivery-slot-finder#disclaimer-about-disappearing-slots) about them. At one point got 20+ "phantom slots" while running the script for 72 hours straight before finally being able to checkout at 2:16am. Wish you luck in getting a slot. Keep me posted on any success/issues you encounter.

**Comment by ginakiele5** [comment] 2020-04-09 03:10
Happy to help out Adrian. I’ll lyk if it happens again!

**Closed as completed** 2020-04-09 05:15 UTC
Labels: question

**Comment by ginakiele5** [comment] 2020-04-09 15:24
Hi Adrian,
Script stopped running. I’ve run your Javascript Youtube instructions several times.  Here’s the error message:

> error "Safari got an error: Can’t get window id 457." number -1728 from window id 457
> 			-- signals that the loop should end
> 			set found_slot to true
> 		else
> 			-- encountered unknown page
> 			-- will navigate back to the cart and from there back to the slot selection page
> 			log "unknown page encountered"
> 			restartCheckout(selected_cart_url, amzn_win_id)
> 		end if
> 	end repeat
> else
> 	log "user did not confirm javascript access was enabled. exiting due to insufficient permissions"
> end if

**Comment by ginakiele5** [comment] 2020-04-09 15:26
BTW I just reran everything and it’s working. Thanks!

**Comment by ginakiele5** [comment] 2020-04-09 17:18
Keep getting errors this morning:
error "Safari got an error: Can’t get window id 794." number -1728 from window id 794

**Comment by ginakiele5** [comment] 2020-04-09 17:47
HI Adrian,
Another error:

error "Safari got an error: Can’t get last tab of window id 923." number -1728 from last tab of window id 923

**Comment by ginakiele5** [comment] 2020-04-09 17:48
This info was above the error message that I just sent you.  I swear we enabled javascript! 

			-- bring Safari window to front and expand to fill screen so delivery slots are clearly visible
			tell application "Safari"
				-- unminimize
				set miniaturized of window id amzn_win_id to false
				-- wait for window to open
				delay 1
				-- maximize window 
				-- this might be useful later on if I want to have it take a screenshot as proof of delivery slots found
				-- Credit for fill to screen: https://macosxautomation.com/applescript/firsttutorial/18.html
				tell application "System Events"
					tell application "Finder" to get the bounds of the window of the desktop
					tell application "Safari" to set the bounds of the front window to ¬
						{0, 22, (3rd item of the result), (4th item of the result)}
				end tell
			end tell
			
			-- signals that the loop should end
			set found_slot to true
		else
			-- encountered unknown page
			-- will navigate back to the cart and from there back to the slot selection page
			log "unknown page encountered"
			restartCheckout(selected_cart_url, amzn_win_id)
		end if
	end repeat
else
	log "user did not confirm javascript access was enabled. exiting due to insufficient permissions"
end if

**Comment by ginakiele5** [comment] 2020-04-09 18:03
Another error:
error "Safari got an error: Can’t get window id 996." number -1728 from window id 996

-- signals that the loop should end
			set found_slot to true
		else
			-- encountered unknown page
			-- will navigate back to the cart and from there back to the slot selection page
			log "unknown page encountered"
			restartCheckout(selected_cart_url, amzn_win_id)
		end if
	end repeat
else
	log "user did not confirm javascript access was enabled. exiting due to insufficient permissions"
end if

**Comment by ginakiele5** [comment] 2020-04-09 18:07
And another: error "Safari got an error: Can’t get window id 1051." number -1728 from window id 1051

**Comment by ahertel** [comment] 2020-04-09 18:09
@ginakiele5 appreciate the updates. Not sure if you saw my comment [above](https://github.com/ahertel/Amazon-Fresh-Whole-Foods-delivery-slot-finder/issues/27#issuecomment-611266202) but could you please follow these steps in [this video](https://youtu.be/wGKfNLzDx-s) I made for you to share the script's log with me? That might help me identify the cause. If that doesn't help, perhaps we can screen-share to get to the bottom of it.

**Comment by ginakiele5** [comment] 2020-04-09 20:00
I did this, still lots of errors today. Thanks.

**Comment by ginakiele5** [comment] 2020-04-11 18:13
Hi Adrian,
I’m back at it. Got this error and cant get script to run.  Thanks.
Gina

Expected end of line, etc. but found identifier.
